/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWebsiteRouteImport } from './routes/_authenticated/website'
import { Route as AuthenticatedTitoRouteImport } from './routes/_authenticated/tito'
import { Route as AuthenticatedSponsorInboxRouteImport } from './routes/_authenticated/sponsor-inbox'
import { Route as AuthenticatedSpeakersRouteImport } from './routes/_authenticated/speakers'
import { Route as AuthenticatedSpeakerSourcingRouteImport } from './routes/_authenticated/speaker-sourcing'
import { Route as AuthenticatedReplyNeededRouteImport } from './routes/_authenticated/reply-needed'
import { Route as AuthenticatedProofingRouteImport } from './routes/_authenticated/proofing'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedMilestonesRouteImport } from './routes/_authenticated/milestones'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedTitoSlugRouteImport } from './routes/_authenticated/tito.$slug'
import { Route as AuthenticatedSpeakersSpeakerIdRouteImport } from './routes/_authenticated/speakers.$speakerId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteRoute = AuthenticatedWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTitoRoute = AuthenticatedTitoRouteImport.update({
  id: '/tito',
  path: '/tito',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSponsorInboxRoute =
  AuthenticatedSponsorInboxRouteImport.update({
    id: '/sponsor-inbox',
    path: '/sponsor-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpeakersRoute = AuthenticatedSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpeakerSourcingRoute =
  AuthenticatedSpeakerSourcingRouteImport.update({
    id: '/speaker-sourcing',
    path: '/speaker-sourcing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReplyNeededRoute =
  AuthenticatedReplyNeededRouteImport.update({
    id: '/reply-needed',
    path: '/reply-needed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProofingRoute = AuthenticatedProofingRouteImport.update({
  id: '/proofing',
  path: '/proofing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMilestonesRoute = AuthenticatedMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTitoSlugRoute = AuthenticatedTitoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedTitoRoute,
} as any)
const AuthenticatedSpeakersSpeakerIdRoute =
  AuthenticatedSpeakersSpeakerIdRouteImport.update({
    id: '/$speakerId',
    path: '/$speakerId',
    getParentRoute: () => AuthenticatedSpeakersRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/proofing': typeof AuthenticatedProofingRoute
  '/reply-needed': typeof AuthenticatedReplyNeededRoute
  '/speaker-sourcing': typeof AuthenticatedSpeakerSourcingRoute
  '/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/sponsor-inbox': typeof AuthenticatedSponsorInboxRoute
  '/tito': typeof AuthenticatedTitoRouteWithChildren
  '/website': typeof AuthenticatedWebsiteRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/tito/$slug': typeof AuthenticatedTitoSlugRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/milestones': typeof AuthenticatedMilestonesRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/proofing': typeof AuthenticatedProofingRoute
  '/reply-needed': typeof AuthenticatedReplyNeededRoute
  '/speaker-sourcing': typeof AuthenticatedSpeakerSourcingRoute
  '/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/sponsor-inbox': typeof AuthenticatedSponsorInboxRoute
  '/tito': typeof AuthenticatedTitoRouteWithChildren
  '/website': typeof AuthenticatedWebsiteRoute
  '/': typeof AuthenticatedIndexRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/tito/$slug': typeof AuthenticatedTitoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/milestones': typeof AuthenticatedMilestonesRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/proofing': typeof AuthenticatedProofingRoute
  '/_authenticated/reply-needed': typeof AuthenticatedReplyNeededRoute
  '/_authenticated/speaker-sourcing': typeof AuthenticatedSpeakerSourcingRoute
  '/_authenticated/speakers': typeof AuthenticatedSpeakersRouteWithChildren
  '/_authenticated/sponsor-inbox': typeof AuthenticatedSponsorInboxRoute
  '/_authenticated/tito': typeof AuthenticatedTitoRouteWithChildren
  '/_authenticated/website': typeof AuthenticatedWebsiteRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/speakers/$speakerId': typeof AuthenticatedSpeakersSpeakerIdRoute
  '/_authenticated/tito/$slug': typeof AuthenticatedTitoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/banners'
    | '/milestones'
    | '/outreach'
    | '/proofing'
    | '/reply-needed'
    | '/speaker-sourcing'
    | '/speakers'
    | '/sponsor-inbox'
    | '/tito'
    | '/website'
    | '/events/$eventId'
    | '/speakers/$speakerId'
    | '/tito/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/banners'
    | '/milestones'
    | '/outreach'
    | '/proofing'
    | '/reply-needed'
    | '/speaker-sourcing'
    | '/speakers'
    | '/sponsor-inbox'
    | '/tito'
    | '/website'
    | '/'
    | '/events/$eventId'
    | '/speakers/$speakerId'
    | '/tito/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/banners'
    | '/_authenticated/milestones'
    | '/_authenticated/outreach'
    | '/_authenticated/proofing'
    | '/_authenticated/reply-needed'
    | '/_authenticated/speaker-sourcing'
    | '/_authenticated/speakers'
    | '/_authenticated/sponsor-inbox'
    | '/_authenticated/tito'
    | '/_authenticated/website'
    | '/_authenticated/'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/speakers/$speakerId'
    | '/_authenticated/tito/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website': {
      id: '/_authenticated/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedWebsiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tito': {
      id: '/_authenticated/tito'
      path: '/tito'
      fullPath: '/tito'
      preLoaderRoute: typeof AuthenticatedTitoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sponsor-inbox': {
      id: '/_authenticated/sponsor-inbox'
      path: '/sponsor-inbox'
      fullPath: '/sponsor-inbox'
      preLoaderRoute: typeof AuthenticatedSponsorInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speakers': {
      id: '/_authenticated/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof AuthenticatedSpeakersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/speaker-sourcing': {
      id: '/_authenticated/speaker-sourcing'
      path: '/speaker-sourcing'
      fullPath: '/speaker-sourcing'
      preLoaderRoute: typeof AuthenticatedSpeakerSourcingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reply-needed': {
      id: '/_authenticated/reply-needed'
      path: '/reply-needed'
      fullPath: '/reply-needed'
      preLoaderRoute: typeof AuthenticatedReplyNeededRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proofing': {
      id: '/_authenticated/proofing'
      path: '/proofing'
      fullPath: '/proofing'
      preLoaderRoute: typeof AuthenticatedProofingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milestones': {
      id: '/_authenticated/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof AuthenticatedMilestonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tito/$slug': {
      id: '/_authenticated/tito/$slug'
      path: '/$slug'
      fullPath: '/tito/$slug'
      preLoaderRoute: typeof AuthenticatedTitoSlugRouteImport
      parentRoute: typeof AuthenticatedTitoRoute
    }
    '/_authenticated/speakers/$speakerId': {
      id: '/_authenticated/speakers/$speakerId'
      path: '/$speakerId'
      fullPath: '/speakers/$speakerId'
      preLoaderRoute: typeof AuthenticatedSpeakersSpeakerIdRouteImport
      parentRoute: typeof AuthenticatedSpeakersRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSpeakersRouteChildren {
  AuthenticatedSpeakersSpeakerIdRoute: typeof AuthenticatedSpeakersSpeakerIdRoute
}

const AuthenticatedSpeakersRouteChildren: AuthenticatedSpeakersRouteChildren = {
  AuthenticatedSpeakersSpeakerIdRoute: AuthenticatedSpeakersSpeakerIdRoute,
}

const AuthenticatedSpeakersRouteWithChildren =
  AuthenticatedSpeakersRoute._addFileChildren(
    AuthenticatedSpeakersRouteChildren,
  )

interface AuthenticatedTitoRouteChildren {
  AuthenticatedTitoSlugRoute: typeof AuthenticatedTitoSlugRoute
}

const AuthenticatedTitoRouteChildren: AuthenticatedTitoRouteChildren = {
  AuthenticatedTitoSlugRoute: AuthenticatedTitoSlugRoute,
}

const AuthenticatedTitoRouteWithChildren =
  AuthenticatedTitoRoute._addFileChildren(AuthenticatedTitoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedMilestonesRoute: typeof AuthenticatedMilestonesRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedProofingRoute: typeof AuthenticatedProofingRoute
  AuthenticatedReplyNeededRoute: typeof AuthenticatedReplyNeededRoute
  AuthenticatedSpeakerSourcingRoute: typeof AuthenticatedSpeakerSourcingRoute
  AuthenticatedSpeakersRoute: typeof AuthenticatedSpeakersRouteWithChildren
  AuthenticatedSponsorInboxRoute: typeof AuthenticatedSponsorInboxRoute
  AuthenticatedTitoRoute: typeof AuthenticatedTitoRouteWithChildren
  AuthenticatedWebsiteRoute: typeof AuthenticatedWebsiteRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedMilestonesRoute: AuthenticatedMilestonesRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedProofingRoute: AuthenticatedProofingRoute,
  AuthenticatedReplyNeededRoute: AuthenticatedReplyNeededRoute,
  AuthenticatedSpeakerSourcingRoute: AuthenticatedSpeakerSourcingRoute,
  AuthenticatedSpeakersRoute: AuthenticatedSpeakersRouteWithChildren,
  AuthenticatedSponsorInboxRoute: AuthenticatedSponsorInboxRoute,
  AuthenticatedTitoRoute: AuthenticatedTitoRouteWithChildren,
  AuthenticatedWebsiteRoute: AuthenticatedWebsiteRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
